In [22]:
# Import Libraries
import numpy as np
from random import randint

In [23]:
# 1D array
array_1d = np.array([1,2,3,5,6], dtype='int32')
array_1d

array([1, 2, 3, 5, 6], dtype=int32)

In [34]:
# 2D array
m = 5
n = 3
array_2d = np.array([[randint(0, 10) for j in range(n)] for i in range(m)], dtype='float32')
array_2d

array([[ 6., 10.,  7.],
       [ 5.,  8.,  3.],
       [ 7.,  0.,  5.],
       [ 9.,  9.,  4.],
       [ 2.,  6.,  5.]], dtype=float32)

In [35]:
# Numebr of dimentions
print(array_1d.ndim)
print(array_2d.ndim)


1
2


In [36]:
# Shape of array
print(array_1d.shape)
print(array_2d.shape)

(5,)
(5, 3)


In [37]:
# Get type
print(array_1d.dtype)
print(array_2d.dtype)

int32
float32


In [39]:
# Number of bytes per item
print(array_1d.itemsize)
print(array_2d.itemsize)

4
4


In [41]:
# Size of array
print(array_1d.size)
print(array_2d.size)

5
15


In [43]:
# Number of bytes utilized nbytes = size * itemsize
print(array_1d.nbytes)
print(array_2d.nbytes)

20
60


In [45]:
# Get spcific element [r, c]
print(array_2d[1, 2])

3.0


In [47]:
# get specific row
print(array_2d[1, :])

[5. 8. 3.]


In [48]:
# get specific column
print(array_2d[:, 2])

[7. 3. 5. 4. 5.]


In [49]:
print(array_2d)

[[ 6. 10.  7.]
 [ 5.  8.  3.]
 [ 7.  0.  5.]
 [ 9.  9.  4.]
 [ 2.  6.  5.]]


In [51]:
# Every alternate in 2nd column
print(array_2d[::2, 1])

[10.  0.  6.]


In [76]:
print(np.zeros((3,1), dtype='int8'), end='\n\n')
print(np.ones((1,2,1)), end='\n\n')
print(np.full((3,), 'za21eds'))
print(np.random.randint(100, 105, size=(2,3)))
print(np.random.random_sample(array_2d.shape))
np.identity(3)
print(np.repeat([array_1d], 3, axis=0))

[[0]
 [0]
 [0]]

[[[1.]
  [1.]]]

['za21eds' 'za21eds' 'za21eds']
[[100 101 101]
 [100 102 101]]
[[0.65950085 0.34783584 0.80162728]
 [0.92275735 0.55883021 0.6156244 ]
 [0.66011153 0.95865373 0.29130287]
 [0.5931845  0.39969013 0.73339728]
 [0.06159848 0.89164154 0.03397519]]
[[1 2 3 5 6]
 [1 2 3 5 6]
 [1 2 3 5 6]]
