In [47]:
# Import Libraries
import numpy as np
from random import randint

In [48]:
# 1D array
array_1d = np.array([1,2,3,5,6], dtype='int32')
array_1d

array([1, 2, 3, 5, 6], dtype=int32)

In [49]:
# 2D array
m = 5
n = 3
array_2d = np.array([[randint(0, 10) for j in range(n)] for i in range(m)], dtype='float32')
array_2d

array([[ 6.,  3., 10.],
       [ 4.,  4.,  4.],
       [ 0., 10., 10.],
       [ 5., 10.,  9.],
       [ 6.,  9.,  4.]], dtype=float32)

In [50]:
# Numebr of dimentions
print(array_1d.ndim)
print(array_2d.ndim)


1
2


In [51]:
# Shape of array
print(array_1d.shape)
print(array_2d.shape)

(5,)
(5, 3)


In [52]:
# Get type
print(array_1d.dtype)
print(array_2d.dtype)

int32
float32


In [53]:
# Number of bytes per item
print(array_1d.itemsize)
print(array_2d.itemsize)

4
4


In [54]:
# Size of array
print(array_1d.size)
print(array_2d.size)

5
15


In [55]:
# Number of bytes utilized nbytes = size * itemsize
print(array_1d.nbytes)
print(array_2d.nbytes)

20
60


In [56]:
# Get spcific element [r, c]
print(array_2d[1, 2])

4.0


In [57]:
# get specific row
print(array_2d[1, :])

[4. 4. 4.]


In [58]:
# get specific column
print(array_2d[:, 2])

[10.  4. 10.  9.  4.]


In [59]:
print(array_2d)

[[ 6.  3. 10.]
 [ 4.  4.  4.]
 [ 0. 10. 10.]
 [ 5. 10.  9.]
 [ 6.  9.  4.]]


In [60]:
# Every alternate in 2nd column
print(array_2d[::2, 1])

[ 3. 10.  9.]


In [61]:
print(np.zeros((3,1), dtype='int8'), end='\n\n')
print(np.ones((1,2,1)), end='\n\n')
print(np.full((3,), 'za21eds'))
print(np.random.randint(100, 105, size=(2,3)))
print(np.random.random_sample(array_2d.shape))
np.identity(3)
print(np.repeat([array_1d], 3, axis=0))

[[0]
 [0]
 [0]]

[[[1.]
  [1.]]]

['za21eds' 'za21eds' 'za21eds']
[[100 104 100]
 [101 103 102]]
[[0.4967822  0.94546571 0.64697687]
 [0.6872806  0.27471569 0.30311042]
 [0.7162192  0.18992726 0.21654584]
 [0.9512879  0.02603913 0.9538329 ]
 [0.20809489 0.97436745 0.44437974]]
[[1 2 3 5 6]
 [1 2 3 5 6]
 [1 2 3 5 6]]


In [62]:
mat = np.ones((5, 5), dtype='int32')
temp = np.zeros((3, 3))
temp[1,1] = 9
mat[1:4, 1:4] = temp.copy()
print(temp)
mat

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

## Math with NumPy

In [63]:
array_1d

array([1, 2, 3, 5, 6], dtype=int32)

In [64]:
array_1d / 2

array([0.5, 1. , 1.5, 2.5, 3. ])

In [65]:
array_1d * 2

array([ 2,  4,  6, 10, 12], dtype=int32)

In [66]:
array_1d ** 2

array([ 1,  4,  9, 25, 36], dtype=int32)

In [67]:
array_1d ** (1/2)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974])

In [68]:
np.sin(array_1d)

array([ 0.84147098,  0.90929743,  0.14112001, -0.95892427, -0.2794155 ])

### Linear Algebra

In [69]:
a = np.full((2, 3), 1)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [70]:
b = np.full((3, 2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [71]:
np.dot(a,b)

array([[6, 6],
       [6, 6]])

In [72]:
np.linalg.det(np.identity(5))

1.0

In [73]:
a = np.array([[1, -3, 3], [3, -5, 3], [6, -6, 4]])
np.linalg.eigvals(a)

array([ 4.+0.00000000e+00j, -2.+1.10465796e-15j, -2.-1.10465796e-15j])

### Statistics

In [74]:
np.min(a, axis=1)

array([-3, -5, -6])

In [75]:
np.sum(a)

6

In [76]:
b = np.zeros((3,3))
np.any(b)

False

### Reorganizing

In [77]:
a

array([[ 1, -3,  3],
       [ 3, -5,  3],
       [ 6, -6,  4]])

In [78]:
np.reshape(a, (9,1))

array([[ 1],
       [-3],
       [ 3],
       [ 3],
       [-5],
       [ 3],
       [ 6],
       [-6],
       [ 4]])

### Vertical stacks

In [79]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
np.vstack([a,b,a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

## Loading from file

In [82]:
data = np.random.randint(0, 100, size=(5, 8), dtype='int32')
np.savetxt('data.csv', data, delimiter=',')
data

array([[95, 64, 61, 51, 93, 74, 29, 28],
       [60,  9, 25, 52, 99, 40,  6, 93],
       [81, 16, 31, 63, 36, 44, 69, 64],
       [57, 99, 96, 11,  5, 99, 64, 92],
       [85, 36, 18, 28, 90, 86, 37, 91]], dtype=int32)

In [93]:
load = np.loadtxt('data.csv', delimiter=',', dtype='int32')
load

array([[95, 64, 61, 51, 93, 74, 29, 28],
       [60,  9, 25, 52, 99, 40,  6, 93],
       [81, 16, 31, 63, 36, 44, 69, 64],
       [57, 99, 96, 11,  5, 99, 64, 92],
       [85, 36, 18, 28, 90, 86, 37, 91]], dtype=int32)

In [95]:
a = np.random.randint(0, 100, size=(6,5))
a

array([[30, 52, 41, 79, 46],
       [44, 39,  8, 31, 54],
       [ 9, 76, 16, 76, 37],
       [62, 22, 74, 46,  5],
       [29, 42, 86, 80, 96],
       [95, 32, 25, 48, 39]])

In [96]:
a[list(range(4)), list(range(1,5))]

array([52,  8, 76,  5])

In [105]:
np.vstack([a[:1, -2:], a[-2:, -2:]])

array([[79, 46],
       [80, 96],
       [48, 39]])