In [7]:
import numpy as np

In [8]:
x = [1,2,3]
npx = np.array(x)
npx

array([1, 2, 3])

In [9]:
npx.reshape(3,1)

array([[1],
       [2],
       [3]])

In [10]:
npx2 = np.random.randint(0, 10, (3,3))
npx2

array([[2, 2, 0],
       [5, 2, 5],
       [3, 0, 5]])

In [11]:
npx3 = np.random.randint(0,10, (3,3))
npx3

array([[0, 8, 1],
       [7, 6, 8],
       [9, 3, 8]])

In [12]:
for rowOf2, rowOf3 in zip(npx2, npx3):
    print(rowOf2,' + ',rowOf3,' = ',rowOf2+rowOf3)

[2 2 0]  +  [0 8 1]  =  [ 2 10  1]
[5 2 5]  +  [7 6 8]  =  [12  8 13]
[3 0 5]  +  [9 3 8]  =  [12  3 13]


In [13]:
npx2[:2,:2]

array([[2, 2],
       [5, 2]])

In [14]:
npx2[:2,::2]

array([[2, 0],
       [5, 5]])

In [15]:
sqr = lambda a: a**2
sqr(npx2)

array([[ 4,  4,  0],
       [25,  4, 25],
       [ 9,  0, 25]], dtype=int32)

In [16]:
np.ones([4,4], int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [18]:
import math

In [19]:
perfect_squares = [i for i in range(100) if math.sqrt(i) == int(math.sqrt(i))]
perfect_squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [20]:
npx2[npx2 > 2] = 5
npx2

array([[2, 2, 0],
       [5, 2, 5],
       [5, 0, 5]])

In [25]:
npx2.reshape(1,9)

array([[2, 2, 0, 5, 2, 5, 5, 0, 5]])