In [7]:
import numpy as np
A = np.random.randint(0, 5, (3,4))
A

array([[2, 4, 0, 3],
       [2, 4, 1, 2],
       [2, 2, 3, 1]])

In [8]:
A.sum(axis=0)

array([ 6, 10,  4,  6])

In [9]:
A.sum(axis=1)

array([9, 9, 8])

In [18]:
B = np.array([[3,5],[6,7]])
C = np.array([[5,2],[4,1]])
B*C

array([[15, 10],
       [24,  7]])

In [19]:
B*C.T

array([[15, 20],
       [12,  7]])

In [20]:
B.T*C

array([[15, 12],
       [20,  7]])

In [21]:
B + 100


array([[103, 105],
       [106, 107]])

In [22]:
B + [100, 200]

array([[103, 205],
       [106, 207]])

In [23]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [25]:
print(a)
print(b)
np.dot(a,b)

[[ 0.73676872 -0.13582517  0.17800005]
 [-0.37999801 -0.97275799  0.52852743]
 [ 0.22308119  1.27842408 -0.99185955]
 [ 0.52643553 -1.82832424 -2.0203148 ]]
[[-1.74636589  0.86976984]
 [-1.64283505  2.00377999]
 [ 0.99594183  0.39066219]]


array([[-0.88625173,  0.43819334],
       [ 2.78807907, -2.07322813],
       [-3.4776557 ,  2.36822786],
       [ 0.07217006, -3.99494236]])

In [28]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[-0.58953729, -0.74820647, -2.04586967],
       [-0.3329359 ,  0.73260934,  0.99203257],
       [-0.19978425,  0.1167507 ,  1.43411178]])